version: "3"

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - database_volume:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maindb
      MYSQL_USER: main
      MYSQL_PASSWORD: rahasia
    networks:
      - database

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - database

networks:
  database:

volumes:
  database_volume: